Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PixelBase.Models;
using PixelBase.Data;


namespace PixelBase.Controllers;

public class SearchController : Controller
{
  private readonly PixelBaseContext _context;
  public SearchController(PixelBaseContext context)
  {
    _context = context;
  }

  public async Task<IActionResult> Index(string query)
  {
    var assets = from a in _context.Asset select a;

    if (!String.IsNullOrEmpty(query))
    {
      assets = assets.Where(s => s.Title!.Contains(query));
    }

    ViewData["SearchQuery"] = query;
    return View(await assets.ToListAsync());
  }

}

Views/Shared/ServerError.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(string.IsNullOrEmpty(ViewData["Title"]?.ToString()) ? "" : ViewData["Title"] + " - ")PixelBase</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/img/pixelbase.svg" alt="Pixelbase" width="30" height="30">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <a class="btn btn-primary text-white rounded-circle ms-auto me-2" asp-area="" asp-controller="Home"
                        asp-action="Index">
                        <i class="bi bi-house-fill"></i>
                    </a>
                    <form class="col-7 col-md-6 col-xl-5 col-xxl-4 me-auto" role="search" asp-controller="Search"
                        asp-action="Index" method="get">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search" name="query"
                                value="@ViewData["SearchQuery"]"
                                style="border-bottom-left-radius: 50rem; border-top-left-radius: 50rem;">
                            <a class="btn btn-primary"
                                style="border-top-right-radius: 50rem; border-bottom-right-radius: 50rem;" asp-area=""
                                asp-controller="Search" asp-action="Index">
                                <i class="bi bi-search"></i>
                            </a>
                        </div>
                    </form>
                    @* <img src="/img/patreon-placeholder.png" class="me-3" height="30"> *@
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="footer text-muted py-4">
        <div class="container d-flex">
            <div>
                &copy; @DateTime.Now.Year - PixelBase<br>
                Made with ♥ by <a href="https://github.com/glacereonyx" class="link-secondary">glacereonyx</a><br>
            </div>
            <div class="ms-auto">
                <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>
    <script src="~/js/bundle.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>